kind: pipeline
type: docker
name: bloom

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  commands:
  - git clone --single-branch --branch $DRONE_SOURCE_BRANCH --depth=1 $DRONE_GIT_HTTP_URL .

- name: build
  image: node:latest
  commands:
  - yarn install --network-timeout 600000
  - yarn build
  when:
    branch:
    - main
    event:
    - push
    - pull_request
    - tag

- name: publish-dev
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: paulwrubel/bloom
    tags:
    - dev
  when:
    branch:
    - main
    event:
    - push

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: paulwrubel/bloom
    tags:
    - latest
  when:
    branch:
    - main
    event:
    - tag
